### ISSUE TITLE
测试同步2

### ISSUE THREAD

**Issue by wizard-xie** [xwz123/test#26]
# 测试从GitHub同步issue到Gitee

```go
if ok {
     fmt.Println("hellow word")
}
```
![picture](https://i-1-lanrentuku.52tup.com/2020/11/30/78b34a0d-6a6e-42a3-a8da-663e1db55cf4.jpg)

**Comment by xwz123** [comment]
**SYNCED PROMPT:**  current issue has been synced with [it](https://gitee.com/cve-manage-test/config/issues/I4YHAM)
