### ISSUE TITLE
test case 3

### ISSUE THREAD

**Issue by wizard-xie** [xwz123/test#28]
# 双向同步服务都启动测试
**这个issue是在github上创建的**

**Comment by xwz123** [comment]
**SYNCED PROMPT:**  current issue has been synced with [it](https://gitee.com/cve-manage-test/config/issues/I4YHMP)

**Comment by xwz123** [comment]
sdcscccc

**Comment by wizard-xie** [comment]
huioiooo

**Comment by wizard-xie** [comment]
# test sync issue comment
**这是中文**
[baidu](https://www.baidu.com)

**Comment by xwz123** [comment]
# This is an issue comment from gitee

**this an english comment**

[baidu] (https://ww.baidu.com)

> Bright moon before bed, suspected frost on the ground.
> raised his head to the moon, bowed his head to think of his hometown.
