### ISSUE TITLE
Test Case 4

### ISSUE THREAD

**Issue by xwz123** [xwz123/test#29]
# Test Bidirectional Synchronization 4

** This issue is created in Gitee. **

**Comment by xwz123** [comment]
**SYNCED PROMPT:**  current issue has been synced with [it](https://gitee.com/cve-manage-test/config/issues/I4YHNJ)

**Comment by wizard-xie** [comment]
this a test sync comment

**Comment by wizard-xie** [comment]
this a test sync comment
