### ISSUE TITLE
Test Case 5 (Including the Comment Synchronization Test)

### ISSUE THREAD

**Issue by xwz123** [xwz123/test#30]
Here's a picture:
![picture] (https://i-1-lanrentuku.52tup.com/2020/11/30/78b34a0d-6a6e-42a3-a8da-663e1db55cf4.jpg)
Here's an English verse:
> Give so much time to improving yourself that you won ' t have time to criticize others.

Here are some expressions:
:zzz: :mask:

Here's a piece of code
```go
if ok {
fmt.Println ("good job")
}
```
There's a table below

| Title 1 | Title 2 | Title 3 | Title 4 |
|-----|------|------|-----|
| 123 | 3456 | Long live China | haha |

Here's a link
[Enter Link Description] (http://www.baidu.com)

**Comment by xwz123** [comment]
**SYNCED PROMPT:**  current issue has been synced with [it](https://gitee.com/cve-manage-test/config/issues/I4YVEJ)

**Comment by xwz123** [comment]
Review synchronization test: Content sync is distorted. Do I need to upgrade the SDK?

**Comment by wizard-xie** [comment]
yes i think so !!!!  😴

**Comment by xwz123** [comment]
[百度](https://www.baidu.com)
